-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 16:04:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema frms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frms` ;

-- -----------------------------------------------------
-- Schema frms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frms` DEFAULT CHARACTER SET utf8 ;
USE `frms` ;

-- -----------------------------------------------------
-- Table `pri_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_permission` ;

CREATE TABLE IF NOT EXISTS `pri_permission` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `pid` BIGINT NULL COMMENT '父id',
  `name` VARCHAR(50) NULL COMMENT '权限名',
  `code` VARCHAR(50) NOT NULL COMMENT '权限编码',
  `description` VARCHAR(1000) NULL DEFAULT NULL COMMENT '权限描述',
  `type` VARCHAR(32) NULL DEFAULT NULL COMMENT '权限类型',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '权限表';

CREATE UNIQUE INDEX `uk_id` ON `pri_permission` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_dept_permission_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_dept_permission_ref` ;

CREATE TABLE IF NOT EXISTS `pri_dept_permission_ref` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `dept_id` BIGINT UNSIGNED NOT NULL COMMENT '部门id',
  `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '部门权限关联表';

CREATE UNIQUE INDEX `uk_id` ON `pri_dept_permission_ref` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_dept` ;

CREATE TABLE IF NOT EXISTS `pri_dept` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `pid` BIGINT NULL COMMENT '父id',
  `name` VARCHAR(50) NULL COMMENT '部门名',
  `code` VARCHAR(50) NOT NULL COMMENT '部门编码',
  `description` VARCHAR(1000) NULL DEFAULT NULL COMMENT '部门描述',
  `type` VARCHAR(32) NULL DEFAULT NULL COMMENT '部门类型',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '部门表';

CREATE UNIQUE INDEX `uk_id` ON `pri_dept` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_user_dept_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_user_dept_ref` ;

CREATE TABLE IF NOT EXISTS `pri_user_dept_ref` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户id',
  `dept_id` BIGINT UNSIGNED NOT NULL COMMENT '部门id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户部门关联表';

CREATE UNIQUE INDEX `uk_id` ON `pri_user_dept_ref` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_user_permission_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_user_permission_ref` ;

CREATE TABLE IF NOT EXISTS `pri_user_permission_ref` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户id',
  `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户权限关联表';

CREATE UNIQUE INDEX `uk_id` ON `pri_user_permission_ref` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_role_permission_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_role_permission_ref` ;

CREATE TABLE IF NOT EXISTS `pri_role_permission_ref` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '权限id',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色权限关联表';

CREATE UNIQUE INDEX `uk_id` ON `pri_role_permission_ref` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_role` ;

CREATE TABLE IF NOT EXISTS `pri_role` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `pid` BIGINT NULL COMMENT '父id',
  `name` VARCHAR(50) NULL COMMENT '角色名',
  `code` VARCHAR(50) NOT NULL COMMENT '角色编码',
  `description` VARCHAR(1000) NULL DEFAULT NULL COMMENT '角色描述',
  `type` VARCHAR(32) NULL DEFAULT NULL COMMENT '角色类型',
  `gmt_create` DATETIME NOT NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';

CREATE UNIQUE INDEX `uk_id` ON `pri_role` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_user_role_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_user_role_ref` ;

CREATE TABLE IF NOT EXISTS `pri_user_role_ref` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户id',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户角色关联表';

CREATE UNIQUE INDEX `uk_id` ON `pri_user_role_ref` (`id` ASC);


-- -----------------------------------------------------
-- Table `pri_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pri_user` ;

CREATE TABLE IF NOT EXISTS `pri_user` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '主键',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(50) NOT NULL COMMENT '密码+盐',
  `realname` VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  `salt` VARCHAR(32) NULL DEFAULT NULL COMMENT '盐',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT '邮箱',
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话',
  `sex` TINYINT(4) NULL DEFAULT NULL COMMENT '性别',
  `status` TINYINT(4) UNSIGNED NULL DEFAULT NULL COMMENT '状态 0:禁用，1:正常',
  `birth` DATETIME NULL DEFAULT NULL COMMENT '生日',
  `gmt_create` DATETIME NULL COMMENT '创建时间',
  `gmt_modified` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';

CREATE UNIQUE INDEX `uk_username` ON `pri_user` (`username` ASC);

CREATE UNIQUE INDEX `uk_id` ON `pri_user` (`id` ASC);
